USE wishlist;

CREATE TABLE IF NOT EXISTS data (
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(32) NOT NULL,
	url VARCHAR(128) NOT NULL,
	comment VARCHAR(512),
	added_on DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (id)
);