USE wishlist;

CREATE TABLE IF NOT EXISTS DATA (
	ID INT NOT NULL,
	NAME VARCHAR(32) NOT NULL,
	URL VARCHAR(128) NOT NULL,
	COMMENT VARCHAR(512),
	ADDED_ON DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (id)
);